[package]
name = "ratelimiter"
version = "0.1.0"
authors = ["mwish <anmmscs_maple@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"

[[bin]]
name = "main"
doc = false
path = "bin/main.rs"