[package]
name = "enum_compare"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bitvec = "0.20"


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false